# Intro a Pandas — Ejercicios

Resolución de los ejercicios de la sección **Ejercicios** del notebook de clase
`intro_to_pandas`, más el bonus de exploración del dataset del Titanic.

In [1]:
import pandas as pd
import numpy as np

## Dataset original

Recreamos el DataFrame que se usó en clase para los ejercicios.

In [2]:
data = {
    'name': ['María', 'Daniel', 'Marisa', 'David', 'Sabrina'],
    'age': [16, 7, 29, None, 33],
    'city': ['Madrid', 'Madrid', 'Málaga', 'Málaga', 'Valladolid'],
    'height': [None, 1.20, 1.60, 2.01, 1.83]
}
df = pd.DataFrame(data)
df

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 1 — Toma el dataframe original y guárdalo como un CSV

In [3]:
CSV_PATH = 'data.csv'
df.to_csv(CSV_PATH, index=False)
print(f'Archivo CSV guardado correctamente en "{CSV_PATH}".')

Archivo CSV guardado correctamente en "data.csv".

### Ejercicio 2 — Lee el archivo CSV

In [4]:
df = pd.read_csv(CSV_PATH)
df

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 3 — Muestra los 3 primeros registros del DataFrame

In [5]:
df.head(3)

     name   age    city  height
0   María  16.0  Madrid     NaN
1  Daniel   7.0  Madrid     1.2
2  Marisa  29.0  Málaga     1.6

### Ejercicio 4 — Muestra los 4 últimos registros del DataFrame

In [6]:
df.tail(4)

      name   age        city  height
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 5 — Número de filas del DataFrame

Como en NumPy, podemos calcularlo de dos formas: con el atributo `.shape` o con `len()`.

In [7]:
n_rows_with_shape = df.shape[0]
n_rows_with_len = len(df)

print(f'Forma 1 (df.shape[0]): {n_rows_with_shape} filas.')
print(f'Forma 2 (len(df)):     {n_rows_with_len} filas.')

Forma 1 (df.shape[0]): 5 filas.
Forma 2 (len(df)):     5 filas.

### Ejercicio 6 — Muestra las estadísticas básicas del DataFrame

In [8]:
df.describe()

             age    height
count   4.000000  4.000000
mean   21.250000  1.660000
std    11.954776  0.349571
min     7.000000  1.200000
25%    13.750000  1.500000
50%    22.500000  1.715000
75%    30.000000  1.875000
max    33.000000  2.010000

### Ejercicio 7 — Datos de la columna `name` y su tipo

In [9]:
name_series = df['name']
print(name_series)
print(f'\nEl tipo de dato de la columna "name" es: {name_series.dtype} (object = strings en pandas).')

0      María
1     Daniel
2     Marisa
3      David
4    Sabrina
Name: name, dtype: str

El tipo de dato de la columna "name" es: str (object = strings en pandas).

### Ejercicio 8 🌶️ — Media de `age` con NumPy

Calculamos la media de la columna `age` usando NumPy (ignorando NaN con `np.nanmean`)
y la comparamos con el resultado de pandas.

In [10]:
mean_age_numpy = np.nanmean(df['age'].values)
mean_age_pandas = df['age'].mean()

print(f'Media con np.nanmean: {mean_age_numpy}')
print(f'Media con pandas:     {mean_age_pandas}')
print(f'¿Coinciden los valores? {mean_age_numpy == mean_age_pandas}')

Media con np.nanmean: 21.25
Media con pandas:     21.25
¿Coinciden los valores? True

### Ejercicio 9 — Edad máxima y mínima

In [11]:
max_age = df['age'].max()
min_age = df['age'].min()

print(f'La edad máxima en el dataset es de {max_age:.0f} años.')
print(f'La edad mínima en el dataset es de {min_age:.0f} años.')

La edad máxima en el dataset es de 33 años.
La edad mínima en el dataset es de 7 años.

### Ejercicio 10 🌶️ — Nombre de la persona con la edad mínima

Usamos `idxmin()` para obtener el índice del valor mínimo y luego `.loc[]`
para localizar la fila completa.

In [12]:
min_age_index = df['age'].idxmin()
youngest_person_name = df.loc[min_age_index, 'name']

print(f'La persona con la edad mínima es {youngest_person_name} con {df.loc[min_age_index, "age"]:.0f} años.')

La persona con la edad mínima es Daniel con 7 años.

### Ejercicio 11 — Filas donde la edad sea mayor a 25

In [13]:
older_than_25_df = df[df['age'] > 25]
older_than_25_df

      name   age        city  height
2   Marisa  29.0      Málaga    1.60
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 12 — Filas donde la gente sea de Málaga

In [14]:
malaga_df = df[df['city'] == 'Málaga']
malaga_df

     name   age    city  height
2  Marisa  29.0  Málaga    1.60
3   David   NaN  Málaga    2.01

### Ejercicio 13 🌶️ — Filas donde la gente sea de Málaga **y** mayor de 25

Combinamos dos condiciones con el operador `&`.

In [15]:
is_from_malaga = df['city'] == 'Málaga'
is_older_than_25 = df['age'] > 25
combined_condition = is_from_malaga & is_older_than_25

malaga_older_df = df[combined_condition]
malaga_older_df

     name   age    city  height
2  Marisa  29.0  Málaga     1.6

### Ejercicio 14 — Máscara de los valores nulos del DataFrame

In [16]:
df.isnull()

    name    age   city  height
0  False  False  False    True
1  False  False  False   False
2  False  False  False   False
3  False   True  False   False
4  False  False  False   False

### Ejercicio 15 — Máscara de los valores **NO** nulos del DataFrame

Usamos `notnull()` (también existe el alias `notna()`).

In [17]:
df.notnull()

   name    age  city  height
0  True   True  True   False
1  True   True  True    True
2  True   True  True    True
3  True  False  True    True
4  True   True  True    True

### Ejercicio 16 — Eliminar los valores nulos del DataFrame

In [18]:
df.dropna()

      name   age        city  height
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 17 — Rellena todos los valores nulos con 1

In [19]:
df.fillna(1)

      name   age        city  height
0    María  16.0      Madrid    1.00
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   1.0      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 18 — Rellena sólo los valores nulos de la columna `age` con 10

Trabajamos sobre una copia para no modificar el DataFrame original.

In [20]:
df_with_age_filled = df.copy()
df_with_age_filled['age'] = df_with_age_filled['age'].fillna(10)
df_with_age_filled

      name   age        city  height
0    María  16.0      Madrid     NaN
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David  10.0      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

### Ejercicio 19 🌶️ — Rellena los nulos de `height` con la media de la columna

In [21]:
df_with_height_filled = df.copy()
mean_height = df_with_height_filled['height'].mean()
df_with_height_filled['height'] = df_with_height_filled['height'].fillna(mean_height)

print(f'La media de la columna height es {mean_height:.4f}.')
df_with_height_filled

La media de la columna height es 1.6600.

      name   age        city  height
0    María  16.0      Madrid    1.66
1   Daniel   7.0      Madrid    1.20
2   Marisa  29.0      Málaga    1.60
3    David   NaN      Málaga    2.01
4  Sabrina  33.0  Valladolid    1.83

---

## BONUS — Exploración del dataset del Titanic

Cargamos el dataset del Titanic directamente desde una URL pública para no
subir ningún CSV al repositorio.

In [22]:
TITANIC_CSV_URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic_df = pd.read_csv(TITANIC_CSV_URL)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### B1 — ¿Qué porcentaje de pasajeros sobrevivió?

In [23]:
survival_rate_pct = titanic_df['Survived'].mean() * 100
print(f'El porcentaje de pasajeros que sobrevivió fue del {survival_rate_pct:.2f}%.')

El porcentaje de pasajeros que sobrevivió fue del 38.38%.

### B2 — ¿Cuál es la edad media de los pasajeros?

In [24]:
mean_passenger_age = titanic_df['Age'].mean()
print(f'La edad media de los pasajeros era de {mean_passenger_age:.2f} años.')

La edad media de los pasajeros era de 29.70 años.

### B3 — ¿Cuántos pasajeros había en cada clase?

In [25]:
passengers_per_class = titanic_df['Pclass'].value_counts().sort_index()
print(passengers_per_class)
print()
for pclass, count in passengers_per_class.items():
    print(f'En {pclass}ª clase viajaban {count} pasajeros.')

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

En 1ª clase viajaban 216 pasajeros.
En 2ª clase viajaban 184 pasajeros.
En 3ª clase viajaban 491 pasajeros.

### B4 — Edad media de los pasajeros que sobrevivieron y de los que no

In [26]:
mean_age_by_survival = titanic_df.groupby('Survived')['Age'].mean()
print(mean_age_by_survival)
print()
print(f'La edad media de los supervivientes fue de {mean_age_by_survival[1]:.2f} años.')
print(f'La edad media de los que no sobrevivieron fue de {mean_age_by_survival[0]:.2f} años.')

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

La edad media de los supervivientes fue de 28.34 años.
La edad media de los que no sobrevivieron fue de 30.63 años.

### B5 — Edad máxima de los pasajeros que sobrevivieron y de los que no

In [27]:
max_age_by_survival = titanic_df.groupby('Survived')['Age'].max()
print(max_age_by_survival)
print()
print(f'La edad máxima entre los supervivientes fue de {max_age_by_survival[1]:.0f} años.')
print(f'La edad máxima entre los que no sobrevivieron fue de {max_age_by_survival[0]:.0f} años.')

Survived
0    74.0
1    80.0
Name: Age, dtype: float64

La edad máxima entre los supervivientes fue de 80 años.
La edad máxima entre los que no sobrevivieron fue de 74 años.

### Extras — Otras exploraciones

#### Tasa de supervivencia por sexo

In [28]:
survival_rate_by_sex = titanic_df.groupby('Sex')['Survived'].mean() * 100
print(survival_rate_by_sex)
print()
for sex, rate in survival_rate_by_sex.items():
    print(f'La tasa de supervivencia de las pasajeras {sex} fue del {rate:.2f}%.')

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

La tasa de supervivencia de las pasajeras female fue del 74.20%.
La tasa de supervivencia de las pasajeras male fue del 18.89%.

#### Tasa de supervivencia por clase

In [29]:
survival_rate_by_class = titanic_df.groupby('Pclass')['Survived'].mean() * 100
print(survival_rate_by_class)
print()
for pclass, rate in survival_rate_by_class.items():
    print(f'La tasa de supervivencia en {pclass}ª clase fue del {rate:.2f}%.')

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

La tasa de supervivencia en 1ª clase fue del 62.96%.
La tasa de supervivencia en 2ª clase fue del 47.28%.
La tasa de supervivencia en 3ª clase fue del 24.24%.

#### Tarifa media por clase

In [30]:
mean_fare_by_class = titanic_df.groupby('Pclass')['Fare'].mean()
print(mean_fare_by_class)
print()
for pclass, avg_fare in mean_fare_by_class.items():
    print(f'La tarifa media en {pclass}ª clase fue de {avg_fare:.2f} libras.')

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

La tarifa media en 1ª clase fue de 84.15 libras.
La tarifa media en 2ª clase fue de 20.66 libras.
La tarifa media en 3ª clase fue de 13.68 libras.